### ISSUE TITLE
Not correct spanish with "h"

### ISSUE THREAD

**Issue by SoftSofter** [datadesk/django-softhyphen#18]
Hello, How i can help you to modify the code of your extension?
The Word with "h" on middle of word dont work correct.
A word for example: ahorrar, output: aho-rrar the correct: a-ho-rrar
http://10ejemplos.com/10-ejemplos-de-palabras-con-hiato
I would like make this change for you.
Thanks.

**Comment by BaniMontoya** [comment]
Im try to understand; you know the diccionary lenguage?,im look that file
have a patterns, but im understad that dont use correct priority of they
and suspenct that is the 1 and 2 numbers on the pattern.
thanks for the information,

2014-06-10 16:26 GMT-05:00
